### PR TITLE
Add kubesec, kubeaudit, grype, kube-dump

### PR DESCRIPTION
**Pull request by patsevanton**
```
binenv install kubesec 
2021-07-25T08:53:17+06:00 WRN version for "kubesec" not specified; using "0.9.2"
fetching kubesec version 0.9.2 100% |███████████████████████████████████████████████████████████████████████████████████████████| (12/12 MB, 8.174 MB/s)        
2021-07-25T08:53:19+06:00 INF "kubesec" (0.9.2) installed
```

### CODE REVIEW

**Comment by patsevanton** [comment]
```
binenv install kubeaudit
2021-07-25T08:59:03+06:00 WRN version for "kubeaudit" not specified; using "0.14.2"
fetching kubeaudit version 0.14.2 100% |███████████████████████████████████████████████████████████████████████████████████████████████████| (8.6/8.6 MB, 6.868 MB/s)        
2021-07-25T08:59:05+06:00 INF "kubeaudit" (0.14.2) installed
```

**Comment by patsevanton** [comment]
```
binenv install grype
2021-07-25T09:04:24+06:00 WRN version for "grype" not specified; using "0.15.0"
fetching grype version 0.15.0 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████| (6.5/6.5 MB, 6.113 MB/s)        
2021-07-25T09:04:26+06:00 INF "grype" (0.15.0) installed
```

**Comment by patsevanton** [comment]
```
binenv install kube-dump
2021-07-25T09:11:29+06:00 WRN version for "kube-dump" not specified; using "1.0.6"
fetching kube-dump version 1.0.6 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████| (20/20 kB, 1.677 MB/s)
2021-07-25T09:11:30+06:00 INF "kube-dump" (1.0.6) installed
```

**Comment by Cleming** [comment]
everything works, thank you @patsevanton ! :tada:

**Pull request merged**
