### PR TITLE
add kubepug, check-tls-cert, kail, k8stail

### PR DESCRIPTION
**Pull request by patsevanton**
```
binenv install kubepug
2021-07-06T20:10:56+06:00 WRN version for "kubepug" not specified; using "1.1.3"
fetching kubepug version 1.1.3 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████| (8.9/8.9 MB, 6.197 MB/s)        
2021-07-06T20:10:58+06:00 INF "kubepug" (1.1.3) installed
```

### CODE REVIEW

**Comment by patsevanton** [comment]
```
binenv install check-tls-cert 
2021-07-14T09:15:00+06:00 WRN version for "check-tls-cert" not specified; using "0.4.1"
fetching check-tls-cert version 0.4.1 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████| (3.8/3.8 MB, 896.260 kB/s)        
2021-07-14T09:15:06+06:00 INF "check-tls-cert" (0.4.1) installed
```

**Comment by patsevanton** [comment]
```
binenv install kail
2021-07-14T13:23:56+06:00 WRN version for "kail" not specified; using "0.15.0"
fetching kail version 0.15.0 100% |█████████████████████████████████████████████████████████████████████████████████████████| (7.9/7.9 MB, 982.483 kB/s)        
2021-07-14T13:24:06+06:00 INF "kail" (0.15.0) installed
```

**Comment by patsevanton** [comment]
```
binenv install k8stail
2021-07-14T13:31:59+06:00 WRN version for "k8stail" not specified; using "0.6.0"
fetching k8stail version 0.6.0 100% |█████████████████████████████████████████████████████████████████████████████████████████████████████| (6.3/6.3 MB, 789.098 kB/s)        
2021-07-14T13:32:08+06:00 INF "k8stail" (0.6.0) installed
```

**Comment by Cleming** [comment]
Everything works! Thank you @patsevanton !

**Pull request merged**
