### PR TITLE
added fzf

### PR DESCRIPTION
**Pull request by deknos**
I added fzf. is this the way it works?

### CODE REVIEW

**Comment by leucos** [comment]
Almost !

Here is the proper url line:

`url: https://github.com/junegunn/fzf/releases/download/{{ .Version }}/fzf-{{ .Version }}-{{ .OS }}_{{ .Arch }}.tar.gz`

(there is no `v` before the first `{{ .Version }}` for fzf).

Could you also add it in the README's list please ?

If you want to test your changes (and assuming you have installed binenv), you can just cp your changes to `~/.config/binenv/distributions.yaml` (YMMV depending on your OS), and issue `binenv update fzf && binenv install fzf`. If all goes well, you're done !  

If for some reason you have messed up with your distributions file and broke `binenv`, you can download a fresh copy running `binenv update --distributions`.

I am sorry we do not have proper instructions for now on how to contribute yet :/ We will fix this asap.

Thanks for your contribution !

**Comment by deknos** [comment]
done. do you want to merge it?

**Comment by Cleming** [comment]
lgtm

```❯ binenv install fzf
2020-11-23T17:27:45+01:00 WRN version for "fzf" not specified; using "0.24.3"
fetching fzf version 0.24.3 100% |███████████████████████████████████| (1.1/1.1 MB, 1.609 MB/s)        
2020-11-23T17:27:47+01:00 INF "fzf" (0.24.3) installed
```
cc. @leucos

**Comment by leucos** [comment]
Awesome, thanks @deknos !

**Pull request merged**
