### PR TITLE
Add exa

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by Cleming** [comment]
Hi @patsevanton 

thank you for your contribution :tada: 

- `cache.json` is automatically generated by the CI, can you revert your change on this file ?
- Can you also add the distribution in the `Supported distributions` section of `README.md` ?

thank you !

**Comment by patsevanton** [comment]
Hi @Cleming 
Update PR

**Comment by Cleming** [comment]
Perfect :pray: 

But doesn't work here 

```
❯ binenv install exa
2021-04-21T15:03:05+02:00 WRN version for "exa" not specified; using "0.10.1"
2021-04-21T15:03:06+02:00 ERR unable to install "exa" (0.10.1) error="unable to download binary at https://github.com/ogham/exa/releases/download/0.10.1/exa-Linux-amd64-0.10.1.zip: 404 Not Found"
```

I think you have to do something like : 

```
  exa:
    description: A modern replacement for ‘ls’.
    map:
      amd64: x86_64
    list:
      type: github-releases
      url: https://api.github.com/repos/ogham/exa/releases
    fetch:
      url: https://github.com/ogham/exa/releases/download/v{{ .Version }}/exa-{{ .OS }}-{{ .Arch }}-v{{ .Version }}.zip
    install:
      type: zip
      binaries:
        - exa
```

You can test it by editing your `~/.config/binenv/distributions.yaml` and then `binenv update exa -f` and `binenv install exa`

**Comment by Cleming** [comment]
lgtm @patsevanton :tada:

**Comment by patsevanton** [comment]
Great! Thanks!

**Review by Cleming — APPROVED** [review]

**Comment by leucos** [comment]
Thanks !

**Pull request merged**
