### PR TITLE
add fd - A simple, fast and user-friendly alternative to 'find'

### PR DESCRIPTION
**Pull request by patsevanton**
```
binenv update fd -f
updating distributions 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1/1, 6139 it/s)

binenv install fd
2021-04-28T08:54:24+06:00 WRN version for "fd" not specified; using "8.2.1"
fetching fd version 8.2.1 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1.1/1.1 MB, 2.648 MB/s)
2021-04-28T08:54:25+06:00 INF "fd" (8.2.1) installed
```

### CODE REVIEW

**Comment by leucos** [comment]
you're on a roll ! thanks lot @patsevanton :+1:

**Comment by patsevanton** [comment]
add app to binenv is simple

**Comment by leucos** [comment]
we will have to make binenv a bit more flexible. For fd, we can not have both linux & macos in the same "distribution", this is rather sad :/

**Comment by patsevanton** [comment]
I dont have macos. I cannot check on macos

**Pull request merged**
