### PR TITLE
Add datree, gitlab-terraform-manager, kdigger, parca, pint, terrascan

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by patsevanton** [comment]
Fixed pint, kdigger. I can check app later. Sorry.

**Comment by patsevanton** [comment]
```
fetching kdigger version 1.0.0 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████| (11/11 MB, 369.376 kB/s)         
2021-10-12T18:17:53+06:00 INF "kdigger" (1.0.0) installed
```

**Comment by patsevanton** [comment]
Fix pint

**Comment by leucos** [comment]
you're killing it @patsevanton , thanks !

**Pull request merged**
