### PR TITLE
add clog-cli, gotty, node-problem-detector, act, sloop, sshproxy

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by patsevanton** [comment]
```
binenv install node-problem-detector
2021-06-13T10:33:24+06:00 WRN version for "node-problem-detector" not specified; using "0.8.8"
fetching node-problem-detector version 0.8.8 100% |███████████████████████████████████████████████████████████████████████████████████████| (29/29 MB, 1.729 MB/s)
2021-06-13T10:33:43+06:00 INF "node-problem-detector" (0.8.8) installed
```

**Comment by patsevanton** [comment]
```
binenv install clog-cli
2021-06-13T11:10:47+06:00 WRN version for "clog-cli" not specified; using "0.9.3"
fetching clog-cli version 0.9.3 100% |████████████████████████████████████████████████████████████████████████████████████████████████| (1.5/1.5 MB, 1016.148 kB/s)
2021-06-13T11:10:49+06:00 INF "clog-cli" (0.9.3) installed
```

**Comment by patsevanton** [comment]
```
binenv install gotty
2021-06-13T11:35:22+06:00 WRN version for "gotty" not specified; using "1.0.1"
fetching gotty version 1.0.1 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████| (2.8/2.8 MB, 1.136 MB/s)
2021-06-13T11:35:26+06:00 INF "gotty" (1.0.1) installed
```

**Comment by patsevanton** [comment]
```
binenv install act
2021-06-13T15:48:41+06:00 WRN version for "act" not specified; using "0.2.23"
fetching act version 0.2.23 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████| (5.4/5.4 MB, 1.604 MB/s)
2021-06-13T15:48:46+06:00 INF "act" (0.2.23) installed
```

**Comment by patsevanton** [comment]
```
binenv install sloop
2021-06-16T16:20:26+06:00 WRN version for "sloop" not specified; using "1.0.0"
fetching sloop version 1.0.0 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████| (56/56 MB, 8.921 MB/s)
2021-06-16T16:20:34+06:00 INF "sloop" (1.0.0) installed
```

**Comment by patsevanton** [comment]
```
 binenv install sshproxy
2021-06-16T19:02:31+06:00 WRN version for "sshproxy" not specified; using "1.3.6"
fetching sshproxy version 1.3.6 100% |████████████████████████████████████████████████████████████████████████████████████████████████████| (23/23 MB, 1.470 MB/s)
2021-06-16T19:02:49+06:00 INF "sshproxy" (1.3.6) installed
```

**Comment by leucos** [comment]
you're on a roll @patsevanton , thanks !!

**Pull request merged**
