### PR TITLE
Add docker-compose

### PR DESCRIPTION
**Pull request by sokraflex**

### CODE REVIEW

**Comment by leucos** [comment]
Hey @sokraflex 
Thanks for the PR, but last time I tried docker-compose, it did not work.
Python does weird tricks when code is packages as an executable and it messes up binenv.

Did you try it ?

**Comment by sokraflex** [comment]
Hey @leucos 
No, but thanks for the hint, I'll try it out.
Could you point me towards a documentation, or explain in short, how I can insert the new bin to my local environment for testing? I don't see a `distributions.yml` in the `~/.binenv` directory...

**Comment by leucos** [comment]
Sure. You can `cp distributions/distributions.yml ~/.config/binenv/` and then `binenv update -f docker-compose`

If it fails, you should be able to `binenv uninstall docker-compose`

**Comment by leucos** [comment]
any progress @sokraflex ?
I guess we're going to close this one for now. I'll reopen if you have good news.

**Pull request closed without merging**
