### PR TITLE
Add sd, dust, rga, grex, peco, xh, shell2http

### PR DESCRIPTION
**Pull request by patsevanton**
```
binenv install sd
2021-06-02T18:44:40+06:00 WRN version for "sd" not specified; using "0.7.6"
fetching sd version 0.7.6 100% |████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1.8/1.8 MB, 1.308 MB/s)
2021-06-02T18:44:43+06:00 INF "sd" (0.7.6) installed
```

### CODE REVIEW

**Comment by patsevanton** [comment]
```
binenv install dust
2021-06-02T19:14:14+06:00 WRN version for "dust" not specified; using "0.5.4"
fetching dust version 0.5.4 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1009/1009 kB, 719.677 kB/s)
2021-06-02T19:14:22+06:00 INF "dust" (0.5.4) installed
```

**Comment by patsevanton** [comment]
```
 binenv install rga
2021-06-03T09:36:50+06:00 WRN version for "rga" not specified; using "0.9.6"
fetching rga version 0.9.6 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (4.8/4.8 MB, 1.558 MB/s)
2021-06-03T09:36:54+06:00 INF "rga" (0.9.6) installed
```

**Comment by patsevanton** [comment]
```
binenv install grex
2021-06-03T10:02:58+06:00 WRN version for "grex" not specified; using "1.2.0"
fetching grex version 1.2.0 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1.8/1.8 MB, 3.276 MB/s)
2021-06-03T10:03:00+06:00 INF "grex" (1.2.0) installed
```

**Comment by patsevanton** [comment]
```
binenv install peco
2021-06-03T11:37:16+06:00 WRN version for "peco" not specified; using "0.5.8"
fetching peco version 0.5.8 100% |██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (2.5/2.5 MB, 3.823 MB/s)
2021-06-03T11:37:17+06:00 INF "peco" (0.5.8) installed
```

**Comment by patsevanton** [comment]
```
binenv install xh
2021-06-03T11:55:21+06:00 WRN version for "xh" not specified; using "0.10.0"
fetching xh version 0.10.0 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (3.2/3.2 MB, 5.265 MB/s)
2021-06-03T11:55:22+06:00 INF "xh" (0.10.0) installed
```

**Comment by patsevanton** [comment]
```
binenv install shell2http
2021-06-03T19:12:46+06:00 WRN version for "shell2http" not specified; using "1.13.0"
fetching shell2http version 1.13.0 100% |███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| (1.8/1.8 MB, 3.554 MB/s)
2021-06-03T19:12:47+06:00 INF "shell2http" (1.13.0) installed
```

**Comment by patsevanton** [comment]
May be merge PR ?

**Comment by leucos** [comment]
Thanks a lot !

**Pull request merged**
